import Head from 'next/head'
import React, {useState, useEffect} from 'react'
import Image from 'next/image'
import { SearchContent, RecommendationSeed } from "spotify-types";
import {signOut, useSession, getSession } from 'next-auth/react'
import useSpotify from '../hooks/useSpotify'
import { useRecoilState } from 'recoil'
import { topTrackState } from '../atoms/topTracksAtom'
import { topArtistState } from '../atoms/topArtistsAtom'
import Layout from '../components/Layout'
import SideBar from '../components/SideBar'

import HomeContent from '../components/HomeContent';
// import type { TrackSearchResponse } from "/spotify-api" 

// interface HomeProps {
//   genres: Array<string>
// }


export default function Home(props) {
  const { data: session, status} = useSession()
  const spotifyApi = useSpotify();
  const [query, setQuery] = useState('')
  const [topArtists, setTopArtists] = useRecoilState(topArtistState)
  const [topTracks, setTopTracks] = useRecoilState(topTrackState)

  // console.log("session in index: ", session)


 useEffect(() => {
  if(spotifyApi.getAccessToken()){
    /* Get a User’s Top Artists*/
    spotifyApi.getMyTopArtists()
      .then(function(data) {
        // console.log(data.body.items);
        setTopArtists(data.body.items)
      }, function(err) {
        console.log('Something went wrong!', err);
      });

    /* Get a User’s Top Tracks*/
    spotifyApi.getMyTopTracks()
    .then(function(data) {
      // console.log(data.body.items);
      setTopTracks(data.body.items)
    }, function(err) {
      console.log('Something went wrong!', err);
    });
  }
 }, [session, spotifyApi])

// console.log("topTracks ", topTracks)
 

  return (
    <div >
      <Head>
        <title>MusicMe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout> 
        <h1 className='text-2xl md:text-3xl xl:text-5xl font-bold text-white'>Top Artists</h1>
        <HomeContent topTracks={topTracks} />
        {/* <div className='text-white'>HELLO WORLDS</div> */}
      </Layout>
      
      

   
    </div>
  )
}


export async function getServerSideProps(context) {
    const session = await getSession(context)

    return {
      props: {
        session,
      }
    }
}