import Head from 'next/head'
import React, {useState, useEffect} from 'react'
import Image from 'next/image'
import { SearchContent, RecommendationSeed } from "spotify-types";
import {signOut, useSession, getSession } from 'next-auth/react'
import useSpotify from '../hooks/useSpotify'
import { useRecoilState } from 'recoil'
import { topTrackState } from '../atoms/topTracksAtom'
import { topArtistState } from '../atoms/topArtistsAtom'
import Layout from '../components/Layout'
// import { UsersTopTracksResponse} from "types/spotify-api"
import HomeContent from '../components/HomeContent';
// import type { TrackSearchResponse } from "/spotify-api" 

interface HomeProps {
  genres: Array<string>
}


export default function Home(props: HomeProps) {
  const { data: session, status} = useSession()
  const spotifyApi = useSpotify();
  const [query, setQuery] = useState('')
  const [topArtists, setTopArtists] = useRecoilState<SpotifyApi.UsersTopArtistsResponse>(topArtistState)
  const [topTracks, setTopTracks] = useRecoilState<SpotifyApi.UsersTopTracksResponse>(topTrackState)

  // console.log("session in index: ", session)


 useEffect(() => {
  if(spotifyApi.getAccessToken()){
    /* Get a User’s Top Artists*/
    spotifyApi.getMyTopArtists()
      .then((data: SpotifyApi.UsersTopArtistsResponse) => {
        // console.log(data.body.items);
        setTopArtists(data)
      }, function(err: unknown) {
        console.log('Something went wrong!', err);
      });

    /* Get a User’s Top Tracks*/
    spotifyApi.getMyTopTracks()
    .then((data: SpotifyApi.UsersTopTracksResponse) => {
      // console.log(data.body.items);
      setTopTracks(data)
    }, function(err: unknown) {
      console.log('Something went wrong!', err);
    });
  }
 }, [session, spotifyApi])

// console.log("topTracks ", topTracks)
 

  return (
    <div >
      <Head>
        <title>MusicMe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout> 
        <h1 className='text-2xl md:text-3xl xl:text-5xl font-bold text-white'>Top Artists</h1>
        {console.log(topTracks.body.items)}
        <HomeContent topTracks={topTracks.body.items} />
        {/* <div className='text-white'>HELLO WORLDS</div> */}
      </Layout>
      
      

   
    </div>
  )
}


export async function getServerSideProps(context: any) {
    const session = await getSession(context)

    return {
      props: {
        session,
      }
    }
}